# Generated by Django 4.2.20 on 2025-03-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
